name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # with:
      #   fetch-depth: 0

    - name: debug
      run: |
        find . -maxdepth 3 -type f -exec ls -lh "{}" \;

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Use cached environment
      id: cache-env
      uses: actions/cache@v2
      with:
        path: |
          ~/.asdf/installs
          ~/.asdf/plugins
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}}

    - name: Set up environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v2.2.0

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-root --no-interaction --no-dev

    - name: Run unit tests
      working-directory: ${{ github.workspace }}
      run: |
        python ./gas-prices-gr/test_scrape_gas_prices_vrisko.py

    - name: Run code coverage
      run: |
        coverage report ${{ github.workspace }}/scrape_gas_prices_vrisko.py
