name: Python CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use cached environment
      id: cache-env
      uses: actions/cache@v2
      with:
        path: |
          ~/.asdf/installs
          ~/.asdf/plugins
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}}

    - name: Set up environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v2.2.0

    - name: Run poetry install
      run: |
        poetry install

    - name: Run unit tests and code coverage
      run: |
        coverage run -m pytest
        coverage report -m
